# -*- coding: utf-8 -*-
"""honors_prototype_client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zuGmWZ37uq5soUTE5NL6338HSb_IvrEQ
"""

!pip3 install requests

cd sample_data

import requests

link = "http://00ec1b9f69ae.ngrok.io/success"


res = requests.post(link, files = {"file":open("happyboy.jpg", 'rb')}, data = {"latitude":"40", "longitude":"60"})
print(res.text)

res1 = requests.post(link, files = {"file":open("surprise.jpg", 'rb')}, data = {"latitude":"43", "longitude":"63"})
print(res1.text)

res2 = requests.post(link, files = {"file":open("happyman.jpg", 'rb')}, data = {"latitude":"50", "longitude":"70"})
print(res2.text)

res3 = requests.post(link, files = {"file":open("peterparker.jpg", 'rb')}, data = {"latitude":"55", "longitude":"75"})
print(res3.text)

res4 = requests.post(link, files = {"file":open("angrywoman.jpg", 'rb')}, data = {"latitude":"75", "longitude":"80"})
print(res4.text)

map_link = "http://00ec1b9f69ae.ngrok.io/map"
final_map = requests.get(map_link)
print(final_map.text)

with open("map2.html", "w") as map:
  map.write(final_map.text)

