# -*- coding: utf-8 -*-
"""honors_server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vGrcgDW8WvDbO0SGAiS1FMBKQasklEil
"""

!pip3 install fer

!pip3 install gmplot

cd sample_data

import gmplot

def plot_map(data):
  gmap3 = gmplot.GoogleMapPlotter(data[0][1], data[0][2], 13)
  for x in data:
    print(x[0]) 
    if x[0] == "happy":
      print("here")
      gmap3.marker(x[1], x[2], color="red")
    elif x[0] == "angry":
      print("In here")
      gmap3.marker(x[1], x[2], color="blue")
    elif x[0] == "sad":
      gmap3.marker(x[1], x[2], color="green")
    elif x[0] == "neutral":
      gmap3.marker(x[1], x[2], color="yellow")
    elif x[0] == "disgust":
      gmap3.marker(x[1], x[2], color="blue")
    elif x[0] == "fear":
      gmap3.marker(x[1], x[2], color="black")
    elif x[0] == "surprise":
      gmap3.marker(x[1], x[2], color="white")
    
  gmap3.draw("final_map.html")

from fer import FER
import matplotlib.pyplot as plt

def img_emote(im_name):
  img = plt.imread(im_name)
  detector = FER(mtcnn=True)
  p = detector.detect_emotions(img)[0]['emotions']
  key = ""
  max = 0
  for x in p.keys():
    if p[x] > max:
      max = p[x]
      key = x
  return key

cd sample_data

pip install flask-ngrok

from flask_ngrok import run_with_ngrok
from flask import *

markers = []

app = Flask(__name__, template_folder="." )
run_with_ngrok(app)
@app.route('/')
def upload():
    return """ <html>
    <head>
        <title>upload</title>
    </head>
    <body>
        <form action = "/success" method = "post" enctype="multipart/form-data">
            <input type="file" name="file" />
                <input name="longitude">
                <input name="latitude">
            <input type = "submit" value="Upload">
        </form>
    </body>
    </html>
   """

@app.route('/success', methods = ['POST'])
def success():
    if request.method == 'POST':
        f = request.files['file']
        lon = request.form['longitude']
        lat = request.form['latitude']
        f.save(f.filename)
        data_emo = (img_emote(f.filename), float(lat), float(lon))
        markers.append(data_emo)
        return str(data_emo)

@app.route('/map')
def see_map():
  print(markers)
  plot_map(markers)
  return render_template("final_map.html")

@app.route('/data')
def check_data():
  return markers


if __name__ == '__main__':
    app.run()

